### ISSUE TITLE
Where is the source? :P

### ISSUE THREAD

**Issue by darkestkhan** [charlie5/lace-prototype-deprecated#1]
Just like in the title, for there is no source code.

**Comment by charlie5** [comment]
Hi,

```
Most components mentioned are in a private prototype repository 
```

(some are more up to date than others).

```
Main idea is to tidy code, and then add, each component in turn, 
```

beginning with the base tier.

**Comment by charlie5** [comment]
Code for the base 'lace' and 'math' components is in.

**Comment by charlie5** [comment]
Code for the base 'xml' component is in.

**Comment by charlie5** [comment]
The collada and openGL code is now in.

**Comment by charlie5** [comment]
The physics code is now in.

**Comment by charlie5** [comment]
The MMI (user interface) code is now in.

That's about it for now.
